// Generated by jextract

package org.libheif.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$21 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$21() {}
    static final VarHandle const$0 = constants$19.const$1.varHandle(MemoryLayout.PathElement.groupElement("color_primary_blue_y"));
    static final VarHandle const$1 = constants$19.const$1.varHandle(MemoryLayout.PathElement.groupElement("color_primary_white_x"));
    static final VarHandle const$2 = constants$19.const$1.varHandle(MemoryLayout.PathElement.groupElement("color_primary_white_y"));
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_nclx_color_profile",
        constants$9.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandleVariadic(
        "heif_nclx_color_profile_alloc",
        constants$0.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_nclx_color_profile_free",
        constants$3.const$4
    );
}


