// Generated by jextract

package org.libheif.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$26 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$26() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_image_get_colorspace",
        constants$2.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_image_get_chroma_format",
        constants$2.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_image_get_width",
        constants$1.const$5
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_image_get_height",
        constants$1.const$5
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "heif_image_get_primary_width",
        constants$2.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_image_get_primary_height",
        constants$2.const$2
    );
}


