// Generated by jextract

package org.libheif.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$22 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$22() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_image_get_color_profile_type",
        constants$2.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_image_get_raw_color_profile_size",
        constants$5.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_image_get_raw_color_profile",
        constants$9.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_image_get_nclx_color_profile",
        constants$9.const$0
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_BYTE.withName("version"),
        JAVA_BYTE.withName("ignore_transformations"),
        MemoryLayout.paddingLayout(6),
        RuntimeHelper.POINTER.withName("start_progress"),
        RuntimeHelper.POINTER.withName("on_progress"),
        RuntimeHelper.POINTER.withName("end_progress"),
        RuntimeHelper.POINTER.withName("progress_user_data"),
        JAVA_BYTE.withName("convert_hdr_to_8bit"),
        MemoryLayout.paddingLayout(7)
    ).withName("heif_decoding_options");
    static final VarHandle const$5 = constants$22.const$4.varHandle(MemoryLayout.PathElement.groupElement("version"));
}


