// Generated by jextract

package org.libheif.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$1 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$1() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_get_version_number_maintenance",
        constants$0.const$2
    );
    static final StructLayout const$1 = MemoryLayout.structLayout(
        JAVA_INT.withName("code"),
        JAVA_INT.withName("subcode"),
        RuntimeHelper.POINTER.withName("message")
    ).withName("heif_error");
    static final VarHandle const$2 = constants$1.const$1.varHandle(MemoryLayout.PathElement.groupElement("code"));
    static final VarHandle const$3 = constants$1.const$1.varHandle(MemoryLayout.PathElement.groupElement("subcode"));
    static final VarHandle const$4 = constants$1.const$1.varHandle(MemoryLayout.PathElement.groupElement("message"));
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(JAVA_INT,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "heif_check_filetype",
        constants$1.const$5
    );
}


