// Generated by jextract

package org.libheif.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$12 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$12() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_ispe_width",
        constants$2.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_ispe_height",
        constants$2.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_image_handle_has_depth_image",
        constants$2.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_number_of_depth_images",
        constants$2.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_list_of_depth_image_IDs",
        constants$8.const$5
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_depth_image_handle",
        constants$9.const$5
    );
}


