// Generated by jextract

package org.libheif.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$40 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$40() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_image_add_plane",
        constants$27.const$0
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_image_set_premultiplied_alpha",
        constants$10.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_image_is_premultiplied_alpha",
        constants$2.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_register_decoder",
        constants$9.const$0
    );
    static final FunctionDescriptor const$4 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("code"),
        JAVA_INT.withName("subcode"),
        RuntimeHelper.POINTER.withName("message")
    ).withName("heif_error"),
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_register_decoder_plugin",
        constants$40.const$4
    );
}


