// Generated by jextract

package org.libheif.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$17 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$17() {}
    static final FunctionDescriptor heif_encoder_release$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_encoder_release$MH = RuntimeHelper.downcallHandle(
        "heif_encoder_release",
        constants$17.heif_encoder_release$FUNC
    );
    static final FunctionDescriptor heif_encoder_get_name$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_encoder_get_name$MH = RuntimeHelper.downcallHandle(
        "heif_encoder_get_name",
        constants$17.heif_encoder_get_name$FUNC
    );
    static final FunctionDescriptor heif_encoder_set_lossy_quality$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("code"),
        Constants$root.C_LONG$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle heif_encoder_set_lossy_quality$MH = RuntimeHelper.downcallHandle(
        "heif_encoder_set_lossy_quality",
        constants$17.heif_encoder_set_lossy_quality$FUNC
    );
    static final FunctionDescriptor heif_encoder_set_lossless$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("code"),
        Constants$root.C_LONG$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle heif_encoder_set_lossless$MH = RuntimeHelper.downcallHandle(
        "heif_encoder_set_lossless",
        constants$17.heif_encoder_set_lossless$FUNC
    );
    static final FunctionDescriptor heif_encoder_set_logging_level$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("code"),
        Constants$root.C_LONG$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle heif_encoder_set_logging_level$MH = RuntimeHelper.downcallHandle(
        "heif_encoder_set_logging_level",
        constants$17.heif_encoder_set_logging_level$FUNC
    );
    static final FunctionDescriptor heif_encoder_list_parameters$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_encoder_list_parameters$MH = RuntimeHelper.downcallHandle(
        "heif_encoder_list_parameters",
        constants$17.heif_encoder_list_parameters$FUNC
    );
}


