// Generated by jextract

package org.libheif.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$5 {

    static final FunctionDescriptor heif_image_handle_release$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle heif_image_handle_release$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_release",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$5.heif_image_handle_release$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_is_primary_image$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle heif_image_handle_is_primary_image$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_is_primary_image",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$5.heif_image_handle_is_primary_image$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_get_width$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle heif_image_handle_get_width$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_get_width",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$5.heif_image_handle_get_width$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_get_height$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle heif_image_handle_get_height$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_get_height",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$5.heif_image_handle_get_height$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_has_alpha_channel$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle heif_image_handle_has_alpha_channel$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_has_alpha_channel",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$5.heif_image_handle_has_alpha_channel$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_is_premultiplied_alpha$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle heif_image_handle_is_premultiplied_alpha$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_is_premultiplied_alpha",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$5.heif_image_handle_is_premultiplied_alpha$FUNC, false
    );
}


