// Generated by jextract

package org.libheif.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$23 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$23() {}
    static final VarHandle const$0 = constants$22.const$4.varHandle(MemoryLayout.PathElement.groupElement("ignore_transformations"));
    static final FunctionDescriptor const$1 = FunctionDescriptor.ofVoid(
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$2 = RuntimeHelper.upcallHandle(heif_decoding_options.start_progress.class, "apply", constants$23.const$1);
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        constants$23.const$1
    );
    static final VarHandle const$4 = constants$22.const$4.varHandle(MemoryLayout.PathElement.groupElement("start_progress"));
    static final MethodHandle const$5 = RuntimeHelper.upcallHandle(heif_decoding_options.on_progress.class, "apply", constants$23.const$1);
}


