// Generated by jextract

package org.libheif.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$37 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$37() {}
    static final VarHandle const$0 = constants$36.const$5.varHandle(MemoryLayout.PathElement.groupElement("version"));
    static final VarHandle const$1 = constants$36.const$5.varHandle(MemoryLayout.PathElement.groupElement("save_alpha_channel"));
    static final VarHandle const$2 = constants$36.const$5.varHandle(MemoryLayout.PathElement.groupElement("macOS_compatibility_workaround"));
    static final VarHandle const$3 = constants$36.const$5.varHandle(MemoryLayout.PathElement.groupElement("save_two_colr_boxes_when_ICC_and_nclx_available"));
    static final VarHandle const$4 = constants$36.const$5.varHandle(MemoryLayout.PathElement.groupElement("output_nclx_profile"));
    static final VarHandle const$5 = constants$36.const$5.varHandle(MemoryLayout.PathElement.groupElement("macOS_compatibility_workaround_no_nclx_profile"));
}


