// Generated by jextract

package org.libheif.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$20 {

    static final FunctionDescriptor heif_encoder_parameter_string_valid_values$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("code"),
        Constants$root.C_LONG$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_encoder_parameter_string_valid_values$MH = RuntimeHelper.downcallHandle(
        "heif_encoder_parameter_string_valid_values",
        constants$20.heif_encoder_parameter_string_valid_values$FUNC, false
    );
    static final FunctionDescriptor heif_encoder_parameter_integer_valid_values$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("code"),
        Constants$root.C_LONG$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_encoder_parameter_integer_valid_values$MH = RuntimeHelper.downcallHandle(
        "heif_encoder_parameter_integer_valid_values",
        constants$20.heif_encoder_parameter_integer_valid_values$FUNC, false
    );
    static final FunctionDescriptor heif_encoder_set_parameter$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("code"),
        Constants$root.C_LONG$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_encoder_set_parameter$MH = RuntimeHelper.downcallHandle(
        "heif_encoder_set_parameter",
        constants$20.heif_encoder_set_parameter$FUNC, false
    );
    static final FunctionDescriptor heif_encoder_get_parameter$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("code"),
        Constants$root.C_LONG$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG$LAYOUT
    );
    static final MethodHandle heif_encoder_get_parameter$MH = RuntimeHelper.downcallHandle(
        "heif_encoder_get_parameter",
        constants$20.heif_encoder_get_parameter$FUNC, false
    );
    static final FunctionDescriptor heif_encoder_has_default$FUNC = FunctionDescriptor.of(Constants$root.C_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_encoder_has_default$MH = RuntimeHelper.downcallHandle(
        "heif_encoder_has_default",
        constants$20.heif_encoder_has_default$FUNC, false
    );
    static final FunctionDescriptor heif_encoding_options_alloc$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle heif_encoding_options_alloc$MH = RuntimeHelper.downcallHandle(
        "heif_encoding_options_alloc",
        constants$20.heif_encoding_options_alloc$FUNC, true
    );
}


