// Generated by jextract

package org.libheif.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$11 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$11() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_width",
        constants$2.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_height",
        constants$2.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_image_handle_has_alpha_channel",
        constants$2.const$2
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_image_handle_is_premultiplied_alpha",
        constants$2.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_luma_bits_per_pixel",
        constants$2.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_chroma_bits_per_pixel",
        constants$2.const$2
    );
}


