// Generated by jextract

package org.libheif.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$4 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$4() {}
    static final FunctionDescriptor const$0 = FunctionDescriptor.of(RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_get_file_mime_type",
        constants$4.const$0
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_context_alloc",
        constants$0.const$0
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_context_free",
        constants$3.const$4
    );
    static final StructLayout const$4 = MemoryLayout.structLayout(
        JAVA_INT.withName("reader_api_version"),
        MemoryLayout.paddingLayout(4),
        RuntimeHelper.POINTER.withName("get_position"),
        RuntimeHelper.POINTER.withName("read"),
        RuntimeHelper.POINTER.withName("seek"),
        RuntimeHelper.POINTER.withName("wait_for_file_size")
    ).withName("heif_reader");
    static final VarHandle const$5 = constants$4.const$4.varHandle(MemoryLayout.PathElement.groupElement("reader_api_version"));
}


