// Generated by jextract

package org.libheif.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class heif_writer {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("writer_api_version"),
        MemoryLayout.paddingLayout(32),
        Constants$root.C_POINTER$LAYOUT.withName("write")
    ).withName("heif_writer");
    public static MemoryLayout $LAYOUT() {
        return heif_writer.$struct$LAYOUT;
    }
    static final VarHandle writer_api_version$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("writer_api_version"));
    public static VarHandle writer_api_version$VH() {
        return heif_writer.writer_api_version$VH;
    }
    public static int writer_api_version$get(MemorySegment seg) {
        return (int)heif_writer.writer_api_version$VH.get(seg);
    }
    public static void writer_api_version$set( MemorySegment seg, int x) {
        heif_writer.writer_api_version$VH.set(seg, x);
    }
    public static int writer_api_version$get(MemorySegment seg, long index) {
        return (int)heif_writer.writer_api_version$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void writer_api_version$set(MemorySegment seg, long index, int x) {
        heif_writer.writer_api_version$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final FunctionDescriptor write$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_LONG$LAYOUT.withName("code"),
        Constants$root.C_LONG$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle write$MH = RuntimeHelper.downcallHandle(
        heif_writer.write$FUNC
    );
    public interface write {

        java.lang.foreign.MemorySegment apply(java.lang.foreign.MemoryAddress _x0, java.lang.foreign.MemoryAddress _x1, long _x2, java.lang.foreign.MemoryAddress _x3);
        static MemorySegment allocate(write fi, MemorySession session) {
            return RuntimeHelper.upcallStub(write.class, fi, heif_writer.write$FUNC, session);
        }
        static write ofAddress(MemoryAddress addr, MemorySession session) {
            MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
            return (java.lang.foreign.MemoryAddress __x0, java.lang.foreign.MemoryAddress __x1, long __x2, java.lang.foreign.MemoryAddress __x3) -> {
                try {
                    return (java.lang.foreign.MemorySegment)heif_writer.write$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)__x0, (java.lang.foreign.Addressable)__x1, __x2, (java.lang.foreign.Addressable)__x3);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle write$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("write"));
    public static VarHandle write$VH() {
        return heif_writer.write$VH;
    }
    public static MemoryAddress write$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)heif_writer.write$VH.get(seg);
    }
    public static void write$set( MemorySegment seg, MemoryAddress x) {
        heif_writer.write$VH.set(seg, x);
    }
    public static MemoryAddress write$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)heif_writer.write$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void write$set(MemorySegment seg, long index, MemoryAddress x) {
        heif_writer.write$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static write write (MemorySegment segment, MemorySession session) {
        return write.ofAddress(write$get(segment), session);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


