// Generated by jextract

package org.libheif.win;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
/**
 * {@snippet :
 * struct heif_reader {
 *     int reader_api_version;
 *     long long (*get_position)(void*);
 *     int (*read)(void*,unsigned long long,void*);
 *     int (*seek)(long long,void*);
 *     enum heif_reader_grow_status (*wait_for_file_size)(long long,void*);
 * };
 * }
 */
public class heif_reader {

    public static MemoryLayout $LAYOUT() {
        return constants$4.const$4;
    }
    public static VarHandle reader_api_version$VH() {
        return constants$4.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int reader_api_version;
     * }
     */
    public static int reader_api_version$get(MemorySegment seg) {
        return (int)constants$4.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int reader_api_version;
     * }
     */
    public static void reader_api_version$set(MemorySegment seg, int x) {
        constants$4.const$5.set(seg, x);
    }
    public static int reader_api_version$get(MemorySegment seg, long index) {
        return (int)constants$4.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void reader_api_version$set(MemorySegment seg, long index, int x) {
        constants$4.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    /**
     * {@snippet :
 * long long (*get_position)(void*);
     * }
     */
    public interface get_position {

        long apply(java.lang.foreign.MemorySegment _x0);
        static MemorySegment allocate(get_position fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$5.const$1, fi, constants$5.const$0, scope);
        }
        static get_position ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0) -> {
                try {
                    return (long)constants$5.const$2.invokeExact(symbol, __x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle get_position$VH() {
        return constants$5.const$3;
    }
    /**
     * Getter for field:
     * {@snippet :
     * long long (*get_position)(void*);
     * }
     */
    public static MemorySegment get_position$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$5.const$3.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * long long (*get_position)(void*);
     * }
     */
    public static void get_position$set(MemorySegment seg, MemorySegment x) {
        constants$5.const$3.set(seg, x);
    }
    public static MemorySegment get_position$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$5.const$3.get(seg.asSlice(index*sizeof()));
    }
    public static void get_position$set(MemorySegment seg, long index, MemorySegment x) {
        constants$5.const$3.set(seg.asSlice(index*sizeof()), x);
    }
    public static get_position get_position(MemorySegment segment, Arena scope) {
        return get_position.ofAddress(get_position$get(segment), scope);
    }
    /**
     * {@snippet :
 * int (*read)(void*,unsigned long long,void*);
     * }
     */
    public interface read {

        int apply(java.lang.foreign.MemorySegment _x0, long _x1, java.lang.foreign.MemorySegment _x2);
        static MemorySegment allocate(read fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$5.const$5, fi, constants$5.const$4, scope);
        }
        static read ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (java.lang.foreign.MemorySegment __x0, long __x1, java.lang.foreign.MemorySegment __x2) -> {
                try {
                    return (int)constants$6.const$0.invokeExact(symbol, __x0, __x1, __x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle read$VH() {
        return constants$6.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int (*read)(void*,unsigned long long,void*);
     * }
     */
    public static MemorySegment read$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$6.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int (*read)(void*,unsigned long long,void*);
     * }
     */
    public static void read$set(MemorySegment seg, MemorySegment x) {
        constants$6.const$1.set(seg, x);
    }
    public static MemorySegment read$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$6.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void read$set(MemorySegment seg, long index, MemorySegment x) {
        constants$6.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static read read(MemorySegment segment, Arena scope) {
        return read.ofAddress(read$get(segment), scope);
    }
    /**
     * {@snippet :
 * int (*seek)(long long,void*);
     * }
     */
    public interface seek {

        int apply(long _x0, java.lang.foreign.MemorySegment _x1);
        static MemorySegment allocate(seek fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$6.const$3, fi, constants$6.const$2, scope);
        }
        static seek ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (long __x0, java.lang.foreign.MemorySegment __x1) -> {
                try {
                    return (int)constants$6.const$4.invokeExact(symbol, __x0, __x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle seek$VH() {
        return constants$6.const$5;
    }
    /**
     * Getter for field:
     * {@snippet :
     * int (*seek)(long long,void*);
     * }
     */
    public static MemorySegment seek$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$6.const$5.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * int (*seek)(long long,void*);
     * }
     */
    public static void seek$set(MemorySegment seg, MemorySegment x) {
        constants$6.const$5.set(seg, x);
    }
    public static MemorySegment seek$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$6.const$5.get(seg.asSlice(index*sizeof()));
    }
    public static void seek$set(MemorySegment seg, long index, MemorySegment x) {
        constants$6.const$5.set(seg.asSlice(index*sizeof()), x);
    }
    public static seek seek(MemorySegment segment, Arena scope) {
        return seek.ofAddress(seek$get(segment), scope);
    }
    /**
     * {@snippet :
 * enum heif_reader_grow_status (*wait_for_file_size)(long long,void*);
     * }
     */
    public interface wait_for_file_size {

        int apply(long _x0, java.lang.foreign.MemorySegment _x1);
        static MemorySegment allocate(wait_for_file_size fi, Arena scope) {
            return RuntimeHelper.upcallStub(constants$7.const$0, fi, constants$6.const$2, scope);
        }
        static wait_for_file_size ofAddress(MemorySegment addr, Arena arena) {
            MemorySegment symbol = addr.reinterpret(arena, null);
            return (long __x0, java.lang.foreign.MemorySegment __x1) -> {
                try {
                    return (int)constants$6.const$4.invokeExact(symbol, __x0, __x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    public static VarHandle wait_for_file_size$VH() {
        return constants$7.const$1;
    }
    /**
     * Getter for field:
     * {@snippet :
     * enum heif_reader_grow_status (*wait_for_file_size)(long long,void*);
     * }
     */
    public static MemorySegment wait_for_file_size$get(MemorySegment seg) {
        return (java.lang.foreign.MemorySegment)constants$7.const$1.get(seg);
    }
    /**
     * Setter for field:
     * {@snippet :
     * enum heif_reader_grow_status (*wait_for_file_size)(long long,void*);
     * }
     */
    public static void wait_for_file_size$set(MemorySegment seg, MemorySegment x) {
        constants$7.const$1.set(seg, x);
    }
    public static MemorySegment wait_for_file_size$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemorySegment)constants$7.const$1.get(seg.asSlice(index*sizeof()));
    }
    public static void wait_for_file_size$set(MemorySegment seg, long index, MemorySegment x) {
        constants$7.const$1.set(seg.asSlice(index*sizeof()), x);
    }
    public static wait_for_file_size wait_for_file_size(MemorySegment segment, Arena scope) {
        return wait_for_file_size.ofAddress(wait_for_file_size$get(segment), scope);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(long len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemorySegment addr, Arena scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


