// Generated by jextract

package org.libheif.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$13 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$13() {}
    static final FunctionDescriptor heif_image_get_height$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle heif_image_get_height$MH = RuntimeHelper.downcallHandle(
        "heif_image_get_height",
        constants$13.heif_image_get_height$FUNC
    );
    static final FunctionDescriptor heif_image_get_primary_width$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_image_get_primary_width$MH = RuntimeHelper.downcallHandle(
        "heif_image_get_primary_width",
        constants$13.heif_image_get_primary_width$FUNC
    );
    static final FunctionDescriptor heif_image_get_primary_height$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_image_get_primary_height$MH = RuntimeHelper.downcallHandle(
        "heif_image_get_primary_height",
        constants$13.heif_image_get_primary_height$FUNC
    );
    static final FunctionDescriptor heif_image_crop$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("code"),
        Constants$root.C_INT$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle heif_image_crop$MH = RuntimeHelper.downcallHandle(
        "heif_image_crop",
        constants$13.heif_image_crop$FUNC
    );
    static final FunctionDescriptor heif_image_get_bits_per_pixel$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle heif_image_get_bits_per_pixel$MH = RuntimeHelper.downcallHandle(
        "heif_image_get_bits_per_pixel",
        constants$13.heif_image_get_bits_per_pixel$FUNC
    );
    static final FunctionDescriptor heif_image_get_bits_per_pixel_range$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle heif_image_get_bits_per_pixel_range$MH = RuntimeHelper.downcallHandle(
        "heif_image_get_bits_per_pixel_range",
        constants$13.heif_image_get_bits_per_pixel_range$FUNC
    );
}


