// Generated by jextract

package org.libheif.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$7 {

    static final FunctionDescriptor heif_image_handle_get_list_of_depth_image_IDs$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle heif_image_handle_get_list_of_depth_image_IDs$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_get_list_of_depth_image_IDs",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$7.heif_image_handle_get_list_of_depth_image_IDs$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_get_depth_image_handle$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_INT.withName("code"),
        C_INT.withName("subcode"),
        C_POINTER.withName("message")
    ).withName("heif_error"),
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle heif_image_handle_get_depth_image_handle$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_get_depth_image_handle",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemorySegment;",
        constants$7.heif_image_handle_get_depth_image_handle$FUNC, false
    );
    static final FunctionDescriptor heif_depth_representation_info_free$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle heif_depth_representation_info_free$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_depth_representation_info_free",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$7.heif_depth_representation_info_free$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_get_depth_image_representation_info$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle heif_image_handle_get_depth_image_representation_info$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_get_depth_image_representation_info",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)I",
        constants$7.heif_image_handle_get_depth_image_representation_info$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_get_number_of_thumbnails$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle heif_image_handle_get_number_of_thumbnails$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_get_number_of_thumbnails",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$7.heif_image_handle_get_number_of_thumbnails$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_get_list_of_thumbnail_IDs$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_POINTER,
        C_INT
    );
    static final MethodHandle heif_image_handle_get_list_of_thumbnail_IDs$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_get_list_of_thumbnail_IDs",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$7.heif_image_handle_get_list_of_thumbnail_IDs$FUNC, false
    );
}


