// Generated by jextract

package org.libheif.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$8 {

    static final FunctionDescriptor heif_image_handle_get_thumbnail$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_INT.withName("code"),
        C_INT.withName("subcode"),
        C_POINTER.withName("message")
    ).withName("heif_error"),
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle heif_image_handle_get_thumbnail$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_get_thumbnail",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemorySegment;",
        constants$8.heif_image_handle_get_thumbnail$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_get_number_of_auxiliary_images$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle heif_image_handle_get_number_of_auxiliary_images$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_get_number_of_auxiliary_images",
        "(Ljdk/incubator/foreign/MemoryAddress;I)I",
        constants$8.heif_image_handle_get_number_of_auxiliary_images$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_get_list_of_auxiliary_image_IDs$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER,
        C_INT,
        C_POINTER,
        C_INT
    );
    static final MethodHandle heif_image_handle_get_list_of_auxiliary_image_IDs$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_get_list_of_auxiliary_image_IDs",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;I)I",
        constants$8.heif_image_handle_get_list_of_auxiliary_image_IDs$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_get_auxiliary_type$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_INT.withName("code"),
        C_INT.withName("subcode"),
        C_POINTER.withName("message")
    ).withName("heif_error"),
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle heif_image_handle_get_auxiliary_type$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_get_auxiliary_type",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemorySegment;",
        constants$8.heif_image_handle_get_auxiliary_type$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_free_auxiliary_types$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle heif_image_handle_free_auxiliary_types$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_free_auxiliary_types",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$8.heif_image_handle_free_auxiliary_types$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_get_auxiliary_image_handle$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_INT.withName("code"),
        C_INT.withName("subcode"),
        C_POINTER.withName("message")
    ).withName("heif_error"),
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle heif_image_handle_get_auxiliary_image_handle$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_image_handle_get_auxiliary_image_handle",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemorySegment;",
        constants$8.heif_image_handle_get_auxiliary_image_handle$FUNC, false
    );
}


