// Generated by jextract

package org.libheif.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$15 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$15() {}
    static final VarHandle const$0 = constants$13.const$0.varHandle(MemoryLayout.PathElement.groupElement("depth_nonlinear_representation_model_size"));
    static final VarHandle const$1 = constants$13.const$0.varHandle(MemoryLayout.PathElement.groupElement("depth_nonlinear_representation_model"));
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_depth_representation_info_free",
        constants$3.const$4
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_depth_image_representation_info",
        constants$3.const$0
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_number_of_thumbnails",
        constants$2.const$2
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_list_of_thumbnail_IDs",
        constants$8.const$5
    );
}


