// Generated by jextract

package org.libheif.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$9 {

    static final FunctionDescriptor heif_image_handle_get_auxiliary_image_handle$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("code"),
        Constants$root.C_INT$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_image_handle_get_auxiliary_image_handle$MH = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_auxiliary_image_handle",
        constants$9.heif_image_handle_get_auxiliary_image_handle$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_get_number_of_metadata_blocks$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_image_handle_get_number_of_metadata_blocks$MH = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_number_of_metadata_blocks",
        constants$9.heif_image_handle_get_number_of_metadata_blocks$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_get_list_of_metadata_block_IDs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle heif_image_handle_get_list_of_metadata_block_IDs$MH = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_list_of_metadata_block_IDs",
        constants$9.heif_image_handle_get_list_of_metadata_block_IDs$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_get_metadata_type$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle heif_image_handle_get_metadata_type$MH = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_metadata_type",
        constants$9.heif_image_handle_get_metadata_type$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_get_metadata_content_type$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle heif_image_handle_get_metadata_content_type$MH = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_metadata_content_type",
        constants$9.heif_image_handle_get_metadata_content_type$FUNC, false
    );
    static final FunctionDescriptor heif_image_handle_get_metadata_size$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle heif_image_handle_get_metadata_size$MH = RuntimeHelper.downcallHandle(
        "heif_image_handle_get_metadata_size",
        constants$9.heif_image_handle_get_metadata_size$FUNC, false
    );
}


