// Generated by jextract

package org.libheif.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$6 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$6() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        constants$5.const$4
    );
    static final VarHandle const$1 = constants$4.const$4.varHandle(MemoryLayout.PathElement.groupElement("read"));
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(JAVA_INT,
        JAVA_LONG,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$3 = RuntimeHelper.upcallHandle(heif_reader.seek.class, "apply", constants$6.const$2);
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        constants$6.const$2
    );
    static final VarHandle const$5 = constants$4.const$4.varHandle(MemoryLayout.PathElement.groupElement("seek"));
}


