// Generated by jextract

package org.libheif.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$17 {

    static final FunctionDescriptor heif_context_get_encoder_for_format$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_INT.withName("code"),
        C_INT.withName("subcode"),
        C_POINTER.withName("message")
    ).withName("heif_error"),
        C_POINTER,
        C_INT,
        C_POINTER
    );
    static final MethodHandle heif_context_get_encoder_for_format$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_context_get_encoder_for_format",
        "(Ljdk/incubator/foreign/MemoryAddress;ILjdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemorySegment;",
        constants$17.heif_context_get_encoder_for_format$FUNC, false
    );
    static final FunctionDescriptor heif_encoder_release$FUNC = FunctionDescriptor.ofVoid(
        C_POINTER
    );
    static final MethodHandle heif_encoder_release$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_encoder_release",
        "(Ljdk/incubator/foreign/MemoryAddress;)V",
        constants$17.heif_encoder_release$FUNC, false
    );
    static final FunctionDescriptor heif_encoder_get_name$FUNC = FunctionDescriptor.of(C_POINTER,
        C_POINTER
    );
    static final MethodHandle heif_encoder_get_name$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_encoder_get_name",
        "(Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemoryAddress;",
        constants$17.heif_encoder_get_name$FUNC, false
    );
    static final FunctionDescriptor heif_encoder_set_lossy_quality$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_INT.withName("code"),
        C_INT.withName("subcode"),
        C_POINTER.withName("message")
    ).withName("heif_error"),
        C_POINTER,
        C_INT
    );
    static final MethodHandle heif_encoder_set_lossy_quality$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_encoder_set_lossy_quality",
        "(Ljdk/incubator/foreign/MemoryAddress;I)Ljdk/incubator/foreign/MemorySegment;",
        constants$17.heif_encoder_set_lossy_quality$FUNC, false
    );
    static final FunctionDescriptor heif_encoder_set_lossless$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_INT.withName("code"),
        C_INT.withName("subcode"),
        C_POINTER.withName("message")
    ).withName("heif_error"),
        C_POINTER,
        C_INT
    );
    static final MethodHandle heif_encoder_set_lossless$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_encoder_set_lossless",
        "(Ljdk/incubator/foreign/MemoryAddress;I)Ljdk/incubator/foreign/MemorySegment;",
        constants$17.heif_encoder_set_lossless$FUNC, false
    );
    static final FunctionDescriptor heif_encoder_set_logging_level$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_INT.withName("code"),
        C_INT.withName("subcode"),
        C_POINTER.withName("message")
    ).withName("heif_error"),
        C_POINTER,
        C_INT
    );
    static final MethodHandle heif_encoder_set_logging_level$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_encoder_set_logging_level",
        "(Ljdk/incubator/foreign/MemoryAddress;I)Ljdk/incubator/foreign/MemorySegment;",
        constants$17.heif_encoder_set_logging_level$FUNC, false
    );
}


