// Generated by jextract

package org.libheif.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
class constants$3 {

    static final FunctionDescriptor heif_context_read_from_memory_without_copy$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("code"),
        Constants$root.C_INT$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_context_read_from_memory_without_copy$MH = RuntimeHelper.downcallHandle(
        "heif_context_read_from_memory_without_copy",
        constants$3.heif_context_read_from_memory_without_copy$FUNC, false
    );
    static final FunctionDescriptor heif_context_read_from_reader$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("code"),
        Constants$root.C_INT$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_context_read_from_reader$MH = RuntimeHelper.downcallHandle(
        "heif_context_read_from_reader",
        constants$3.heif_context_read_from_reader$FUNC, false
    );
    static final FunctionDescriptor heif_context_get_number_of_top_level_images$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_context_get_number_of_top_level_images$MH = RuntimeHelper.downcallHandle(
        "heif_context_get_number_of_top_level_images",
        constants$3.heif_context_get_number_of_top_level_images$FUNC, false
    );
    static final FunctionDescriptor heif_context_is_top_level_image_ID$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle heif_context_is_top_level_image_ID$MH = RuntimeHelper.downcallHandle(
        "heif_context_is_top_level_image_ID",
        constants$3.heif_context_is_top_level_image_ID$FUNC, false
    );
    static final FunctionDescriptor heif_context_get_list_of_top_level_image_IDs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle heif_context_get_list_of_top_level_image_IDs$MH = RuntimeHelper.downcallHandle(
        "heif_context_get_list_of_top_level_image_IDs",
        constants$3.heif_context_get_list_of_top_level_image_IDs$FUNC, false
    );
    static final FunctionDescriptor heif_context_get_primary_image_ID$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("code"),
        Constants$root.C_INT$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_context_get_primary_image_ID$MH = RuntimeHelper.downcallHandle(
        "heif_context_get_primary_image_ID",
        constants$3.heif_context_get_primary_image_ID$FUNC, false
    );
}


