// Generated by jextract

package org.libheif.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.CLinker.*;
class constants$16 {

    static final FunctionDescriptor heif_encoder_descriptor_get_compression_format$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle heif_encoder_descriptor_get_compression_format$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_encoder_descriptor_get_compression_format",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$16.heif_encoder_descriptor_get_compression_format$FUNC, false
    );
    static final FunctionDescriptor heif_encoder_descriptor_supports_lossy_compression$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle heif_encoder_descriptor_supports_lossy_compression$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_encoder_descriptor_supports_lossy_compression",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$16.heif_encoder_descriptor_supports_lossy_compression$FUNC, false
    );
    static final FunctionDescriptor heif_encoder_descriptor_supports_lossless_compression$FUNC = FunctionDescriptor.of(C_INT,
        C_POINTER
    );
    static final MethodHandle heif_encoder_descriptor_supports_lossless_compression$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_encoder_descriptor_supports_lossless_compression",
        "(Ljdk/incubator/foreign/MemoryAddress;)I",
        constants$16.heif_encoder_descriptor_supports_lossless_compression$FUNC, false
    );
    static final FunctionDescriptor heif_context_get_encoder$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        C_INT.withName("code"),
        C_INT.withName("subcode"),
        C_POINTER.withName("message")
    ).withName("heif_error"),
        C_POINTER,
        C_POINTER,
        C_POINTER
    );
    static final MethodHandle heif_context_get_encoder$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_context_get_encoder",
        "(Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;Ljdk/incubator/foreign/MemoryAddress;)Ljdk/incubator/foreign/MemorySegment;",
        constants$16.heif_context_get_encoder$FUNC, false
    );
    static final FunctionDescriptor heif_have_decoder_for_format$FUNC = FunctionDescriptor.of(C_INT,
        C_INT
    );
    static final MethodHandle heif_have_decoder_for_format$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_have_decoder_for_format",
        "(I)I",
        constants$16.heif_have_decoder_for_format$FUNC, false
    );
    static final FunctionDescriptor heif_have_encoder_for_format$FUNC = FunctionDescriptor.of(C_INT,
        C_INT
    );
    static final MethodHandle heif_have_encoder_for_format$MH = RuntimeHelper.downcallHandle(
        heif_h.LIBRARIES, "heif_have_encoder_for_format",
        "(I)I",
        constants$16.heif_have_encoder_for_format$FUNC, false
    );
}


