// Generated by jextract

package org.libheif.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$31 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$31() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_encoder_descriptor_supports_lossy_compression",
        constants$2.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_encoder_descriptor_supports_lossless_compression",
        constants$2.const$2
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_context_get_encoder",
        constants$7.const$2
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(JAVA_INT,
        JAVA_INT
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "heif_have_decoder_for_format",
        constants$31.const$3
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_have_encoder_for_format",
        constants$31.const$3
    );
}


