// Generated by jextract

package org.libheif.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$23 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$23() {}
    static final FunctionDescriptor heif_image_is_premultiplied_alpha$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_image_is_premultiplied_alpha$MH = RuntimeHelper.downcallHandle(
        "heif_image_is_premultiplied_alpha",
        constants$23.heif_image_is_premultiplied_alpha$FUNC
    );
    static final FunctionDescriptor heif_register_decoder$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("code"),
        Constants$root.C_INT$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_register_decoder$MH = RuntimeHelper.downcallHandle(
        "heif_register_decoder",
        constants$23.heif_register_decoder$FUNC
    );
    static final FunctionDescriptor heif_register_decoder_plugin$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("code"),
        Constants$root.C_INT$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_register_decoder_plugin$MH = RuntimeHelper.downcallHandle(
        "heif_register_decoder_plugin",
        constants$23.heif_register_decoder_plugin$FUNC
    );
    static final FunctionDescriptor heif_register_encoder_plugin$FUNC = FunctionDescriptor.of(MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("code"),
        Constants$root.C_INT$LAYOUT.withName("subcode"),
        Constants$root.C_POINTER$LAYOUT.withName("message")
    ).withName("heif_error"),
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_register_encoder_plugin$MH = RuntimeHelper.downcallHandle(
        "heif_register_encoder_plugin",
        constants$23.heif_register_encoder_plugin$FUNC
    );
    static final FunctionDescriptor heif_encoder_descriptor_supportes_lossy_compression$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_encoder_descriptor_supportes_lossy_compression$MH = RuntimeHelper.downcallHandle(
        "heif_encoder_descriptor_supportes_lossy_compression",
        constants$23.heif_encoder_descriptor_supportes_lossy_compression$FUNC
    );
    static final FunctionDescriptor heif_encoder_descriptor_supportes_lossless_compression$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle heif_encoder_descriptor_supportes_lossless_compression$MH = RuntimeHelper.downcallHandle(
        "heif_encoder_descriptor_supportes_lossless_compression",
        constants$23.heif_encoder_descriptor_supportes_lossless_compression$FUNC
    );
}


