// Generated by jextract

package org.libheif.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$28 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$28() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_image_get_plane",
        constants$27.const$5
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_image_scale_image",
        constants$25.const$2
    );
    static final FunctionDescriptor const$2 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("code"),
        JAVA_INT.withName("subcode"),
        RuntimeHelper.POINTER.withName("message")
    ).withName("heif_error"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_LONG
    );
    static final MethodHandle const$3 = RuntimeHelper.downcallHandle(
        "heif_image_set_raw_color_profile",
        constants$28.const$2
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "heif_image_set_nclx_color_profile",
        constants$9.const$0
    );
    static final MethodHandle const$5 = RuntimeHelper.downcallHandle(
        "heif_image_release",
        constants$3.const$4
    );
}


