// Generated by jextract

package org.libheif.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
final class constants$39 {

    // Suppresses default constructor, ensuring non-instantiability.
    private constants$39() {}
    static final MethodHandle const$0 = RuntimeHelper.downcallHandle(
        "heif_context_assign_thumbnail",
        constants$7.const$2
    );
    static final MethodHandle const$1 = RuntimeHelper.downcallHandle(
        "heif_context_add_exif_metadata",
        constants$35.const$3
    );
    static final MethodHandle const$2 = RuntimeHelper.downcallHandle(
        "heif_context_add_XMP_metadata",
        constants$35.const$3
    );
    static final FunctionDescriptor const$3 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("code"),
        JAVA_INT.withName("subcode"),
        RuntimeHelper.POINTER.withName("message")
    ).withName("heif_error"),
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER,
        JAVA_INT,
        RuntimeHelper.POINTER,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$4 = RuntimeHelper.downcallHandle(
        "heif_context_add_generic_metadata",
        constants$39.const$3
    );
    static final FunctionDescriptor const$5 = FunctionDescriptor.of(MemoryLayout.structLayout(
        JAVA_INT.withName("code"),
        JAVA_INT.withName("subcode"),
        RuntimeHelper.POINTER.withName("message")
    ).withName("heif_error"),
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        JAVA_INT,
        RuntimeHelper.POINTER
    );
    static final MethodHandle const$6 = RuntimeHelper.downcallHandle(
        "heif_image_create",
        constants$39.const$5
    );
}


