// Generated by jextract

package org.libheif.linuxosx;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import jdk.incubator.foreign.*;
import static jdk.incubator.foreign.ValueLayout.*;
public class heif_reader {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("reader_api_version"),
        MemoryLayout.paddingLayout(32),
        Constants$root.C_POINTER$LAYOUT.withName("get_position"),
        Constants$root.C_POINTER$LAYOUT.withName("read"),
        Constants$root.C_POINTER$LAYOUT.withName("seek"),
        Constants$root.C_POINTER$LAYOUT.withName("wait_for_file_size")
    ).withName("heif_reader");
    public static MemoryLayout $LAYOUT() {
        return heif_reader.$struct$LAYOUT;
    }
    static final VarHandle reader_api_version$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("reader_api_version"));
    public static VarHandle reader_api_version$VH() {
        return heif_reader.reader_api_version$VH;
    }
    public static int reader_api_version$get(MemorySegment seg) {
        return (int)heif_reader.reader_api_version$VH.get(seg);
    }
    public static void reader_api_version$set( MemorySegment seg, int x) {
        heif_reader.reader_api_version$VH.set(seg, x);
    }
    public static int reader_api_version$get(MemorySegment seg, long index) {
        return (int)heif_reader.reader_api_version$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void reader_api_version$set(MemorySegment seg, long index, int x) {
        heif_reader.reader_api_version$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final FunctionDescriptor get_position$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle get_position$MH = RuntimeHelper.downcallHandle(
        heif_reader.get_position$FUNC, false
    );
    public interface get_position {

        long apply(jdk.incubator.foreign.MemoryAddress x0);
        static NativeSymbol allocate(get_position fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(get_position.class, fi, heif_reader.get_position$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;)J", scope);
        }
        static get_position ofAddress(MemoryAddress addr, ResourceScope scope) {
            NativeSymbol symbol = NativeSymbol.ofAddress("get_position::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (jdk.incubator.foreign.MemoryAddress x0) -> {
                try {
                    return (long)heif_reader.get_position$MH.invokeExact(symbol, (jdk.incubator.foreign.Addressable)x0);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle get_position$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("get_position"));
    public static VarHandle get_position$VH() {
        return heif_reader.get_position$VH;
    }
    public static MemoryAddress get_position$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)heif_reader.get_position$VH.get(seg);
    }
    public static void get_position$set( MemorySegment seg, MemoryAddress x) {
        heif_reader.get_position$VH.set(seg, x);
    }
    public static MemoryAddress get_position$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)heif_reader.get_position$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void get_position$set(MemorySegment seg, long index, MemoryAddress x) {
        heif_reader.get_position$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static get_position get_position (MemorySegment segment, ResourceScope scope) {
        return get_position.ofAddress(get_position$get(segment), scope);
    }
    static final FunctionDescriptor read$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle read$MH = RuntimeHelper.downcallHandle(
        heif_reader.read$FUNC, false
    );
    public interface read {

        int apply(jdk.incubator.foreign.MemoryAddress x0, long x1, jdk.incubator.foreign.MemoryAddress x2);
        static NativeSymbol allocate(read fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(read.class, fi, heif_reader.read$FUNC, "(Ljdk/incubator/foreign/MemoryAddress;JLjdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static read ofAddress(MemoryAddress addr, ResourceScope scope) {
            NativeSymbol symbol = NativeSymbol.ofAddress("read::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (jdk.incubator.foreign.MemoryAddress x0, long x1, jdk.incubator.foreign.MemoryAddress x2) -> {
                try {
                    return (int)heif_reader.read$MH.invokeExact(symbol, (jdk.incubator.foreign.Addressable)x0, x1, (jdk.incubator.foreign.Addressable)x2);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle read$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("read"));
    public static VarHandle read$VH() {
        return heif_reader.read$VH;
    }
    public static MemoryAddress read$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)heif_reader.read$VH.get(seg);
    }
    public static void read$set( MemorySegment seg, MemoryAddress x) {
        heif_reader.read$VH.set(seg, x);
    }
    public static MemoryAddress read$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)heif_reader.read$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void read$set(MemorySegment seg, long index, MemoryAddress x) {
        heif_reader.read$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static read read (MemorySegment segment, ResourceScope scope) {
        return read.ofAddress(read$get(segment), scope);
    }
    static final FunctionDescriptor seek$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle seek$MH = RuntimeHelper.downcallHandle(
        heif_reader.seek$FUNC, false
    );
    public interface seek {

        int apply(long x0, jdk.incubator.foreign.MemoryAddress x1);
        static NativeSymbol allocate(seek fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(seek.class, fi, heif_reader.seek$FUNC, "(JLjdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static seek ofAddress(MemoryAddress addr, ResourceScope scope) {
            NativeSymbol symbol = NativeSymbol.ofAddress("seek::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (long x0, jdk.incubator.foreign.MemoryAddress x1) -> {
                try {
                    return (int)heif_reader.seek$MH.invokeExact(symbol, x0, (jdk.incubator.foreign.Addressable)x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle seek$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("seek"));
    public static VarHandle seek$VH() {
        return heif_reader.seek$VH;
    }
    public static MemoryAddress seek$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)heif_reader.seek$VH.get(seg);
    }
    public static void seek$set( MemorySegment seg, MemoryAddress x) {
        heif_reader.seek$VH.set(seg, x);
    }
    public static MemoryAddress seek$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)heif_reader.seek$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void seek$set(MemorySegment seg, long index, MemoryAddress x) {
        heif_reader.seek$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static seek seek (MemorySegment segment, ResourceScope scope) {
        return seek.ofAddress(seek$get(segment), scope);
    }
    static final FunctionDescriptor wait_for_file_size$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle wait_for_file_size$MH = RuntimeHelper.downcallHandle(
        heif_reader.wait_for_file_size$FUNC, false
    );
    public interface wait_for_file_size {

        int apply(long x0, jdk.incubator.foreign.MemoryAddress x1);
        static NativeSymbol allocate(wait_for_file_size fi, ResourceScope scope) {
            return RuntimeHelper.upcallStub(wait_for_file_size.class, fi, heif_reader.wait_for_file_size$FUNC, "(JLjdk/incubator/foreign/MemoryAddress;)I", scope);
        }
        static wait_for_file_size ofAddress(MemoryAddress addr, ResourceScope scope) {
            NativeSymbol symbol = NativeSymbol.ofAddress("wait_for_file_size::" + Long.toHexString(addr.toRawLongValue()), addr, scope);
return (long x0, jdk.incubator.foreign.MemoryAddress x1) -> {
                try {
                    return (int)heif_reader.wait_for_file_size$MH.invokeExact(symbol, x0, (jdk.incubator.foreign.Addressable)x1);
                } catch (Throwable ex$) {
                    throw new AssertionError("should not reach here", ex$);
                }
            };
        }
    }

    static final VarHandle wait_for_file_size$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("wait_for_file_size"));
    public static VarHandle wait_for_file_size$VH() {
        return heif_reader.wait_for_file_size$VH;
    }
    public static MemoryAddress wait_for_file_size$get(MemorySegment seg) {
        return (jdk.incubator.foreign.MemoryAddress)heif_reader.wait_for_file_size$VH.get(seg);
    }
    public static void wait_for_file_size$set( MemorySegment seg, MemoryAddress x) {
        heif_reader.wait_for_file_size$VH.set(seg, x);
    }
    public static MemoryAddress wait_for_file_size$get(MemorySegment seg, long index) {
        return (jdk.incubator.foreign.MemoryAddress)heif_reader.wait_for_file_size$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void wait_for_file_size$set(MemorySegment seg, long index, MemoryAddress x) {
        heif_reader.wait_for_file_size$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static wait_for_file_size wait_for_file_size (MemorySegment segment, ResourceScope scope) {
        return wait_for_file_size.ofAddress(wait_for_file_size$get(segment), scope);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment allocate(ResourceScope scope) { return allocate(SegmentAllocator.nativeAllocator(scope)); }
    public static MemorySegment allocateArray(int len, ResourceScope scope) {
        return allocateArray(len, SegmentAllocator.nativeAllocator(scope));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, ResourceScope scope) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, scope); }
}


